[tool.poetry]
name = "tasklist"
version = "0.1.0"
description = ""
authors = ["shailist <shailist2000@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
